### ISSUE TITLE
Error Pane View styling has issues when using the 'One Dark' theme.

### ISSUE THREAD

**Issue by ctolkien** [ctolkien/omnisharp-atom#2]

**Comment by willl** [comment]
Probably only a small issue. Noticed that the "Omnisharp output" window had no issues (it also has a slightly different background and font colour to the other panes).

Turned on the dev tools (View > Developer > Toggle Developer Tools) and found that if I set a colour to the inset-panel things showed up again.

The issue seems to be related to using the One Dark UI Theme and is a theme that is supposed to work well with other syntax themes.

Not entirely sure if this is an Omnisharp Atom issue, or a One Dark theme issue.

**Comment by ctolkien** [comment]
@willl  - did we (well, you :D) figure out if this was a theme or omnisharp-atom issue? Should we perhaps push the issue over to the upstream repo?

**Comment by willl** [comment]
No longer seemed like an issue the last time my local omnisharp-atom worked (this morning). Due to not having the lodash module, omnisharp-atom

**Comment by ctolkien** [comment]
Good enough! Closing :dancers:
